### ISSUE TITLE
[ASK] Downloading firmware into new MCU

### ISSUE THREAD

**Issue by handiko** [astuder/dAISy#15]
Hi Adrian,
My name is Handiko. I want to make your dAISy hardware on my own. I have read in your https://github.com/astuder/dAISy/tree/master/Firmware that to download the firmware, as I understand, the MCU needs to be flashed with the bootloader first. Is that true? If I want to make my own PCB and solder my new MSP430F5502 MCU, can I just use the Daisy_hw4_fw4_15.txt file? Do I still need the bootloader? Any info will be very much appreciated. Thank you and great project!

**Comment by astuder** [comment]
Hi Handiko,

The files and documentation in the Firmware folder are for the USB version of the dAISy, which is a device that I sell. 

The basic AIS receiver documented in the root and KiCad folder of this repository is the foundation of that product, but doesn't support USB. Instead it uses UART to output AIS as a serial data stream. Implementing a USB device would require quite a bit of additional work.

For development purposes I program my MSP430s by using a LaunchPad dev board like [MSP-EXP430F5529LP](https://www.ti.com/tool/MSP-EXP430F5529LP), connecting power, ground, RST and TEST to my own board. TI's Code Composer Studio and UniFlash tool recognize LaunchPads as programmers.

I hope this answers your question. You're welcome to contact me through the email address on my profile page if you have more questions.

Best Regards,
Adrian

**Comment by handiko** [comment]
Hi Adrian,
I have further questions but I'm sorry I can't find your email on your profile page. It doesn't show up on my end. Could you please kindle provide your email address? Thank you.

Regards, 
Handiko

**Comment by astuder** [comment]
Oh, for some unknown reason the email disappeared from my profile. It's now back, a few lines under the profile bio. You must be logged in to see it.

**Comment by astuder** [comment]
Sorry, just noticed that I now can only use the email associated with my GitHub account instead of an arbitrary email address. 👎

I don't want to publish the former, so I had to remove it again. You can contact me at adrian at adrianstuder dot com.
