### ISSUE TITLE
Radio stops to receive data

### ISSUE THREAD

**Issue by astuder** [astuder/dAISy#4]
Sometimes RX CLK and DATA stop. With some radio configurations this happens more often than others. Not reproducible.

Enable watchdog timer and reset as preventive measure?

**Comment by nazmibojan** [comment]
Had this issue been updated in the latest code in GitHub?

Regards,
Rian

**Comment by nazmibojan** [comment]
I'm sorry, I'm new on GitHub and couldn't see update history in branch section before.
I apologize.

Regards,
Rian
