### ISSUE TITLE
uart_send_string() problem

### ISSUE THREAD

**Issue by nazmibojan** [astuder/dAISy#7]
Hello Astuder!
I have one question about send string over uart. In main.c we can see:

uart_send_string("dAISy 0.2 started\r\n");

after radio_get_chip_status().
If I unplugged the dAISy receiver, I could see blinking led that indicate the error of radio_get_chip_status().
But if I plugged the dAISy I couldn't find 'dAISy 0.2 started' printed in my serial terminal.
How could it happen?
Sorry for the noobs question.

Regards,
Rian

**Comment by astuder** [comment]
Hi Rian,

Unless you reset/restart dAISy with a serial terminal open, the startup message will be lost. If you are using a LaunchPad, you may be able to see the message when you press the reset button.

Regards,
Adrian

**Comment by nazmibojan** [comment]
It works!
Thanks Astuder.
Sorry for the noobs question :D

Regards,
Rian

**Comment by astuder** [comment]
no problem
