### ISSUE TITLE
Error when Importing dAISy AIS Project in CCS v6

### ISSUE THREAD

**Issue by nazmibojan** [astuder/dAISy#8]
Hello Astuder,
Thanks for sharing the codes. When I imported the codes in CCS v6 I got this error:

  _Error: Import failed for project 'dAISy' because its meta-data cannot be interpreted. Please contact support._

Any solution?
Thanks.

Salam,
Nazmi

**Comment by astuder** [comment]
Downloading the project as ZIP from Github and importing works for me with CSS 6.1.

PS: Please only use Github issues for actual bugs. Questions like these, any questions actually, are better handled in the dAISy thread on the 43oh forum.
http://forum.43oh.com/topic/4833-potm-daisy-a-simple-ais-receiver/
