### ISSUE TITLE
NRZI encoding

### ISSUE THREAD

**Issue by zerodamage** [astuder/dAISy#9]
Hi 

I'm trying to replicate some of your work here, but I cannot figure out how to interpret the usage of NRZI in AIS. The wikipedia article on AIS signals indicate that only the payload is NRZI encoded, if this is wrong, please let me know so we can get that corrected...

Best Regards

**Comment by astuder** [comment]
If that's what Wikipedia says, it's wrong. Every bit is NRZI encoded, including preamble and start/end flags. In contrast, bit stuffing only applies to the payload between start and end flag.

**Comment by zerodamage** [comment]
Alright, I will edit the page then, thanks for the quick reply 👍

**Comment by astuder** [comment]
Just checked the Wikipedia article. A lot of new content since I last looked. 

The description of multi-slot messages can also be read in the wrong way. Long messages aren't really broken up but keep going until they are done (CRC, end flag), which may span multiple slots.

**Comment by zerodamage** [comment]
I'm working on the other bits, feel free to correct that with your knowledge :)
